api:
  url: "http://203.253.128.181:11004/entities/"
  params:
    datasetId: "temperatureDisaster_1"
  headers:
    Accept: "application/ld+json"
    Link: "<https://raw.githubusercontent.com/ooosm/context/refs/heads/main/KMAWeather.jsonld>"

ssh:
  ssh_host: "3.37.105.126"
  ssh_port: 22
  ssh_username: "ubuntu"
  remote_bind_address:
    host: "icuh-rds.cd7bwwfid5u3.ap-northeast-2.rds.amazonaws.com"
    port: 3306
  local_bind_address:
    host: "127.0.0.1"
    port: 3307

database:
  user: "dasom"
  password: "dasom123"
  name: "DT_CLIMATE_CHANGE"
